name: Generate ASCCI workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: List files
        run: ls -ltra

      - name: Executing shell script 
        run: ./ascii-script.sh
