name: Generate ASCCI workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Executing cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

      - name: Upload Dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying...
